# TH 2nd Mad Lib Program
userList = []

while True:  
    print("1. New user story\n2. Load previous story\n3. Exit")
    user_input = int(input("Input the number for the option you want: "))
    if user_input == 1:

        print("------------------------------------------------------")
        user_name = input("Give me your name: ")
        print("------------------------------------------------------")
        print("------------------------------------------------------")
        name = input("Give me a name: ")
        print("------------------------------------------------------")
        print("------------------------------------------------------")
        plural_noun = input("Give me a plural noun: ")
        print("------------------------------------------------------")
        print("------------------------------------------------------")
        food_item = input("Give me a food item: ")
        print("------------------------------------------------------")
        print("------------------------------------------------------")
        emotion = input("Give me an emotion: ")
        print("------------------------------------------------------")
        print("------------------------------------------------------")
        verb_end_with_ing = input("Give me a verb that ends with ing: ")
        print("------------------------------------------------------")
        print("------------------------------------------------------")
        adjective = input("Give me an adjective: ")
        print("------------------------------------------------------")
        print("------------------------------------------------------")
        strange_movement = input("Give me a strange movement: ")
        print("------------------------------------------------------")
        print("------------------------------------------------------")
        number = int(input("Give me a number: "))
        print("------------------------------------------------------")
        print("------------------------------------------------------")
        type_of_drink = input("Give me a type of drink: ")
        print("------------------------------------------------------")
        print("------------------------------------------------------")
        object = input("Give me an object: ")
        print("------------------------------------------------------")
        print("------------------------------------------------------")
        celebrity = input("Give me the name of a celebrity: ")
        print("------------------------------------------------------")
        print("------------------------------------------------------")
        strange_superpower = input("Give me a strange superpower: ")
        print("------------------------------------------------------")
        print("------------------------------------------------------")
        exclamation = input("Give me an exclamation: ")
        print("------------------------------------------------------")
        print("------------------------------------------------------")
        made_up_word = input("Give me a made up word: ")
        print("------------------------------------------------------")
        print("------------------------------------------------------")
        noun = input("Give me a noun: ")
        print("------------------------------------------------------")
        print("------------------------------------------------------")
        past_tense_verb = input("Give me a past tense verb: ")
        print("------------------------------------------------------")
        print("------------------------------------------------------")
        body_part_plural = input("Give me the plural version of a body part: ")
        print("------------------------------------------------------")
        print("------------------------------------------------------")
        ridculous_adjective = input("Give me a ridiculous adjective: ")
        print("------------------------------------------------------")
        print("------------------------------------------------------")
        verb_end_ed = input("give me a verb ending with ed: ")
        print("------------------------------------------------------")
        print("Here is your story.")
        print("------------------------------------------------------")
        sentence = "Last night my best friend " + name + " came over for \na sleepover. We brought our favorite " + plural_noun + " and ordered extra \n" + food_item + ", just like always. Everything was going great until we started \nfeeling really " + emotion + " while we were " + verb_end_with_ing + ". Suddenly, a " + adjective + " \nlight filled the toom and we saw a " + strange_movement + " outside \nthe window. We looked outside and saw " + str(number) + " aliens  standing \nnext to a glowing spaceship -- holding " + type_of_drink + " and a " + object + ". \nOne of them looked kind of like " + celebrity + " but with \nthree eyes and the ability to " + strange_superpower + '.\n"' + exclamation + '!" we shouted, but the leader just said, "' + made_up_word + '" \nand floated into the kitchen. Apperently, they has traveled across \nthe galaxy in search of the sacred ' + noun + ". We had \none. I " + past_tense_verb + " it last week. Then the wierdest thing \nhappened -- they started " + strange_movement + " and dancing with their " + body_part_plural + "Before \nleaving they stole all our " + plural_noun + ". After that, things got \neven more " + ridculous_adjective + ". They " + verb_end_ed + " into a cloud of \nglitter and dissapeared. So yeah, Pretty normal sleepover."
        print("------------------------------------------------------")
        print(sentence)
        print("------------------------------------------------------")
        userList.append(user_name)
        userList.append(sentence)
    elif user_input == 2:
            print("------------------------------------------------------")
            user = input("What is your name? ")
            print("------------------------------------------------------")
            for i in range(len(userList)):
                if userList[i] == user:
                     print("------------------------------------------------------")
                     print("Hello again " + user + " your story is:\n\n" + userList[i+1])
                     print("------------------------------------------------------")
    elif user_input == 3:
         raise SystemExit
                 


