# TH 2nd Mad Lib Program

print("------------------------------------------------------")
name = input("Give me a name: ")
print("------------------------------------------------------")
print("------------------------------------------------------")
plural_noun = input("Give me a plural noun: ")
print("------------------------------------------------------")
print("------------------------------------------------------")
food_item = input("Give me a food item: ")
print("------------------------------------------------------")
print("------------------------------------------------------")
emotion = input("Give me an emotion: ")
print("------------------------------------------------------")
print("------------------------------------------------------")
verb_end_with_ing = input("Give me a verb that ends with ing: ")
print("------------------------------------------------------")
print("------------------------------------------------------")
adjective = input("Give me an adjective: ")
print("------------------------------------------------------")
print("------------------------------------------------------")
strange_movement = input("Give me a strange movement: ")
print("------------------------------------------------------")
print("------------------------------------------------------")
number = int(input("Give me a number: "))
print("------------------------------------------------------")
print("------------------------------------------------------")
type_of_drink = input("Give me a type of drink: ")
print("------------------------------------------------------")
print("------------------------------------------------------")
object = input("Give me an object: ")
print("------------------------------------------------------")
print("------------------------------------------------------")
celebrity = input("Give me the name of a celebrity: ")
print("------------------------------------------------------")
print("------------------------------------------------------")
strange_superpower = input("Give me a strange superpower: ")
print("------------------------------------------------------")
print("------------------------------------------------------")
exclamation = input("Give me an exclamation: ")
print("------------------------------------------------------")
print("------------------------------------------------------")
made_up_word = input("Give me a made up word: ")
print("------------------------------------------------------")
print("------------------------------------------------------")
noun = input("Give me a noun: ")
print("------------------------------------------------------")
print("------------------------------------------------------")
past_tense_verb = input("Give me a past tense verb: ")
print("------------------------------------------------------")
print("------------------------------------------------------")
body_part_plural = input("Give me the plural version of a body part: ")
print("------------------------------------------------------")
print("------------------------------------------------------")
ridculous_adjective = input("Give me a ridiculous adjective: ")
print("------------------------------------------------------")
print("------------------------------------------------------")
verb_end_ed = input("give me a verb ending with ed: ")
print("------------------------------------------------------")

sentence = "Last night my best friend " + name + " came over for a sleepover. We brought our favorite " + plural_noun + " and ordered extra " + food_item + ", "

# story but finished Last night, my best friend [1. Person’s name] came over for a sleepover. We brought our favorite [2. Plural noun] and ordered extra [3. Food item], just like always.Everything was going great until we started feeling really [4. Emotion] while [5. Verb ending in “-ing”]. Suddenly, a [6. Adjective] light filled the room and we saw a [7. Weird alien movement] outside the window.We looked outside and saw [8. Number] aliens standing next to a glowing spaceship — holding [9. Type of drink] and a [10. Random object]. One of them looked kind of like [11. Celebrity name], but with three eyes and the ability to [12. Weird superpower].“[13. Exclamation]!” we shouted, but the leader just said, “[14. Made-up alien word]” and floated into the kitchen.Apparently, they had traveled across the galaxy in search of the sacred [15. Noun]. We had one. I [16. Verb (past tense)] it last week.Then the weirdest thing happened — they started [17. Another weird alien movement] and dancing with their **[18. Body part]**s.Before leaving, they stole all our [2. Plural noun] and left behind a sticky note that just said “[7. Weird alien movement].”After that, things got even more [19. Ridiculous adjective]. They [20. Verb ending in “-ed”] into a cloud of glitter and disappeared.So yeah. Pretty normal sleepover.